branch-defaults:
  master:
    environment: production
    group_suffix: null
global:
  application_name: pdxactivist
  branch: null
  default_ec2_keyname: jhelwig-yubikey-pdxactivist
  default_platform: Ruby 2.2 (Passenger Standalone)
  default_region: us-west-2
  profile: pdxactivist
  repository: null
  sc: git
